### ISSUE TITLE
BUG: surefire throwing a NullPointerException when running parallel zohhak tests

### ISSUE THREAD

**Issue by seepick** [piotrturski/zohhak#14]
when running a zohhak enabled junit test with the maven surefire plugin and:
1. enabling **parallel tests** and
2. having a **linefeed character** in a testwith value
then a NullPointerException will be thrown in [ConcurrentRunListener:135](https://github.com/apache/maven-surefire/blob/surefire-2.19.1/surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/ConcurrentRunListener.java#L135) with the following stacktrace:
```
Caused by: java.lang.NullPointerException
	at org.apache.maven.surefire.junitcore.ConcurrentRunListener.testStarting(ConcurrentRunListener.java:135)
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.testStarted(JUnit4RunListener.java:91)
	at org.junit.runner.notification.SynchronizedRunListener.testStarted(SynchronizedRunListener.java:49)
	at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:121)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:118)
	at org.apache.maven.surefire.common.junit4.Notifier.fireTestStarted(Notifier.java:100)
	at org.junit.internal.runners.model.EachTestNotifier.fireTestStarted(EachTestNotifier.java:42)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:323)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

if you either disable parallel tests (1.) or remove the linefeed char (2.) then the build will pass again.

in order to reproduce (and debug) the error i've created a test project here: https://github.com/christophpickl/zohhak_parallel_bug

my specs:
* Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
* Java version: 1.8.0_102, vendor: Oracle Corporation
* Default locale: en_US, platform encoding: UTF-8
* OS name: "mac os x", version: "10.12.1", arch: "x86_64", family: "mac"
* JUnit 4.12 (latest)
* Zohhak 1.1.1 (latest)
* Surefire plugin 2.19.1 (latest)
* Surefire provider: surefire-junit47-2.19.1

any suggestions or hints whats going wrong here?! is it zohhak, the surefire junit provider, or surefire itself? IMHO it might be enough to replace the linefeed in the zohhak runner, as the value will become part of the "artificial test method name".

**Comment by piotrturski** [comment]
first guess is bad handling strange test names by tools that execute junit. but it may be also some limitation of junit itself and therefore zohhak should obey to this limitation. anyway, i'll take a look in some spare time. thanks for test project, will be very useful and speed up the process

**Comment by seepick** [comment]
thanks for the quick reply. "strange test names ... execute junit" sounds reasonable. might be the case that the parallel surefire junit provider is somehow different from the non-parallel thingy. anyway...

if i can be of any assistance, just tell me, i am willing the help as far as i am able to...

**Comment by piotrturski** [comment]
i reported this to surefire: https://issues.apache.org/jira/browse/SUREFIRE-1305

**Comment by piotrturski** [comment]
it's going to be fixed in surefire plugin 2.19.2. currently you can use snapshot:

```
<pluginRepositories>
    <pluginRepository>
        <id>apache.snapshots</id>
        <url>http://repository.apache.org/snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```
and
```
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.19.2-20161202.055334-98</version>
```

**Comment by seepick** [comment]
wow, great news, much appreciated 👍 
i'll give it a try with my company's project where this bug popped up, very first thing on monday.
